[project]
name = "project-module"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "pydantic>=2.10.6,<3.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
