name: test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  find_changed_packages:
    uses: ./.github/workflows/finding_changed_package.yml

  run_tests:
    needs: find_changed_packages
    if: needs.find_changed_packages.outputs.packages != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
        with:
          version: "0.8.19"

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --dev --all-groups

      - name: Running pytest
        run: |
          ZERO_COV_DIRS=()        # 例外パッケージが生まれたら追記
          failures=0
          for dir in ${{ needs.find_changed_packages.outputs.packages }}; do
            echo "▶︎ Testing $dir"
            cov_threshold=25
            for skip in "${ZERO_COV_DIRS[@]}"; do
              [ "$dir" = "$skip" ] && cov_threshold=0.01 && break
            done
            uv run pytest -v "$dir"
          done
          exit $failures
